const TOGGLE_DASHBOARD_STATUS_VISIBILITY = 'TOGGLE_DASHBOARD_STATUS_VISIBILITY';
const TOGGLE_REGION_SELECT_VISIBILITY = 'TOGGLE_REGION_SELECT_VISIBILITY';

export { TOGGLE_DASHBOARD_STATUS_VISIBILITY, TOGGLE_REGION_SELECT_VISIBILITY };

export function toggleDashboardStatusVisibility() {
	return {
		type: 'TOGGLE_DASHBOARD_STATUS_VISIBILITY'
	};
}

export function toggleRegionSelectVisibility() {
	return {
		type: 'TOGGLE_REGION_SELECT_VISIBILITY'
	};
}
