const SET_DASHBOARD_CURRENT_TAB_OVERVIEW = 'SET_DASHBOARD_CURRENT_TAB_OVERVIEW';
const SET_DASHBOARD_CURRENT_TAB_ANALYTICS =
	'SET_DASHBOARD_CURRENT_TAB_ANALYTICS';
const SET_DASHBOARD_CURRENT_TAB_DATA = 'SET_DASHBOARD_CURRENT_TAB_DATA';
const SET_DASHBOARD_CURRENT_TAB_ALERTS = 'SET_DASHBOARD_CURRENT_TAB_ALERTS';
const SET_DASHBOARD_CURRENT_TAB_ACCOUNT = 'SET_DASHBOARD_CURRENT_TAB_ACCOUNT';
const SET_DASHBOARD_CURRENT_TAB_HARDWARE = 'SET_DASHBOARD_CURRENT_TAB_HARDWARE';

export {
	SET_DASHBOARD_CURRENT_TAB_OVERVIEW,
	SET_DASHBOARD_CURRENT_TAB_ANALYTICS,
	SET_DASHBOARD_CURRENT_TAB_DATA,
	SET_DASHBOARD_CURRENT_TAB_ALERTS,
	SET_DASHBOARD_CURRENT_TAB_ACCOUNT,
	SET_DASHBOARD_CURRENT_TAB_HARDWARE
};

export function setDashboardViewToOverview() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_OVERVIEW'
	};
}

export function setDashboardViewToAnalytics() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ANALYTICS'
	};
}

export function setDashboardViewToData() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_DATA'
	};
}

export function setDashboardViewToAlerts() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ALERTS'
	};
}

export function setDashboardViewToAccount() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ACCOUNT'
	};
}

export function setDashboardViewToHardware() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_HARDWARE'
	};
}
