const SET_DASHBOARD_CURRENT_TAB_OVERVIEW = 'SET_DASHBOARD_CURRENT_TAB_OVERVIEW';
const SET_DASHBOARD_CURRENT_TAB_ANALYTICS =
	'SET_DASHBOARD_CURRENT_TAB_ANALYTICS';
const SET_DASHBOARD_CURRENT_TAB_DATA = 'SET_DASHBOARD_CURRENT_TAB_DATA';
const SET_DASHBOARD_CURRENT_TAB_ALERTS = 'SET_DASHBOARD_CURRENT_TAB_ALERTS';
const SET_DASHBOARD_CURRENT_TAB_ACCOUNT = 'SET_DASHBOARD_CURRENT_TAB_ACCOUNT';
const SET_DASHBOARD_CURRENT_TAB_HARDWARE = 'SET_DASHBOARD_CURRENT_TAB_HARDWARE';
const SET_DASHBOARD_STATUS_VIEW = 'SET_DASHBOARD_STATUS_VIEW';

const TOGGLE_DASHBOARD_STATUS_VISIBILITY = 'TOGGLE_DASHBOARD_STATUS_VISIBILITY';
const TOGGLE_REGION_SELECT_VISIBILITY = 'TOGGLE_REGION_SELECT_VISIBILITY';

const SET_LOADING = 'SET_LOADING';

export {
	SET_DASHBOARD_CURRENT_TAB_OVERVIEW,
	SET_DASHBOARD_CURRENT_TAB_ANALYTICS,
	SET_DASHBOARD_CURRENT_TAB_DATA,
	SET_DASHBOARD_CURRENT_TAB_ALERTS,
	SET_DASHBOARD_CURRENT_TAB_ACCOUNT,
	SET_DASHBOARD_CURRENT_TAB_HARDWARE,
	SET_DASHBOARD_STATUS_VIEW,
	TOGGLE_DASHBOARD_STATUS_VISIBILITY,
	TOGGLE_REGION_SELECT_VISIBILITY,
	SET_LOADING
};

export function setLoading(bool) {
	return {
		type: 'SET_LOADING',
		bool
	};
}

export function setDashboardViewToOverview() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_OVERVIEW'
	};
}

export function setDashboardViewToAnalytics() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ANALYTICS'
	};
}

export function setDashboardViewToData() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_DATA'
	};
}

export function setDashboardViewToAlerts() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ALERTS'
	};
}

export function setDashboardViewToAccount() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_ACCOUNT'
	};
}

export function setDashboardViewToHardware() {
	return {
		type: 'SET_DASHBOARD_CURRENT_TAB_HARDWARE'
	};
}

export function setDashboardStatusView(view) {
	return {
		type: 'SET_DASHBOARD_STATUS_VIEW',
		view
	};
}

export function toggleDashboardStatusVisibility() {
	return {
		type: 'TOGGLE_DASHBOARD_STATUS_VISIBILITY'
	};
}

export function toggleRegionSelectVisibility() {
	return {
		type: 'TOGGLE_REGION_SELECT_VISIBILITY'
	};
}
