# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc54445425ec58cfba8b67ae9177c337c819972173aa9296a4c1d31319924ef15d67f64acfcbc3515b822d0972cb3eaa71eadf0d2e83470d486a1a8af22590b6
  secret_gmail_username: "drewjamesandre@gmail.com"
  secret_gmail_password: "Hobbes1990"
  secret_gmail_domain: "palmos.co"

test:
  secret_key_base: ec08de2697ffaebc17ea118c7cbbb0a8c14df6367a73bbce3d25d7f66f3b9494e7c9c8e252ad9328551d5dee54425dce95e8e07eea32b8eb6f5de8020f012f78
  secret_gmail_username: "drewjamesandre@gmail.com"
  secret_gmail_password: "Hobbes1990"
  secret_gmail_domain: "palmos.co"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
